hyperskill_project:
  id: 33
  ide_files: https://stepik.org/media/attachments/lesson/204875/additional_files.json
  is_template_based: false
  use_ide: true
stages:
- id: 175
  step: 5329
- id: 176
  step: 5330
- id: 177
  step: 5331
- id: 178
  step: 5332
- id: 179
  step: 5333
- id: 180
  step: 5334
topics:
  0:
  - title: Introduction to Java
    theory_id: 3500
  - title: Basic literals
    theory_id: 3522
  - title: Overview of the basic program
    theory_id: 3521
  - title: Printing data
    theory_id: 3749
  1:
  - title: Computer programming
    theory_id: 8739
  - title: Introduction to operating systems
    theory_id: 9704
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and options
    theory_id: 9746
  - title: Types and variables
    theory_id: 3518
  - title: Comments
    theory_id: 3520
  - title: Naming variables
    theory_id: 3513
  - title: Scanning the input
    theory_id: 9055
  - title: Arithmetic operations
    theory_id: 3519
  - title: Integer types and operations
    theory_id: 3565
  - title: Increment and decrement
    theory_id: 5008
  - title: Characters
    theory_id: 3514
  - title: String
    theory_id: 3523
  - title: Write, compile, and run
    theory_id: 3739
  - title: JVM, JRE, and JDK
    theory_id: 3499
  - title: Running programs on your computer
    theory_id: 3746
  2:
  - title: Boolean and logical operations
    theory_id: 3516
  - title: Relational operators
    theory_id: 3512
  - title: Conditional statement
    theory_id: 3503
  3:
  - title: Units of information
    theory_id: 6865
  - title: Binary numbers
    theory_id: 5544
  - title: IDE
    theory_id: 3805
  - title: Sizes and ranges
    theory_id: 3532
  - title: Type casting
    theory_id: 3510
  - title: Switch statement
    theory_id: 3504
  - title: The for-loop
    theory_id: 3505
  - title: The while and do-while loops
    theory_id: 3498
  - title: Branching statements
    theory_id: 3507
  - title: Defining methods
    theory_id: 3590
  - title: IntelliJ IDEA
    theory_id: 3801
  - title: IDEA Basics
    theory_id: 5819
  - title: EduTools
    theory_id: 5839
  5:
  - title: Introduction to OOP
    theory_id: 3614
  - title: Primitive and reference types
    theory_id: 5035
  - title: Final variables
    theory_id: 7427
  - title: Array
    theory_id: 3511
  - title: Iterating over arrays
    theory_id: 3602
  - title: Defining classes
    theory_id: 3618
  - title: Constructor
    theory_id: 3535
  - title: Instance methods
    theory_id: 3495
  - title: Static members
    theory_id: 3534
  - title: Enum
    theory_id: 8429
